GET http://localhost:5170/GetAll


###
GET http://localhost:5170/GetById/1

### Создать
POST http://localhost:5170/Create
Content-Type: application/json

{
  "amount": 150,
  "category": "food"
}


###
DELETE  http://localhost:5170/Delete/3
