GET http://localhost:5170/GetAll


###
GET http://localhost:5170/GetById/3

### Создать
POST http://localhost:5170/Create
Content-Type: application/json

{
  "amount": 633,
  "category": "transport",
  "createdAt": "2026-09-17"
}


###
DELETE  http://localhost:5170/Delete/3
